services:
  postgres:
    image: postgres:16-alpine
    container_name: kelbet_til_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kelbet_til
    volumes:
      - kelbet_til_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  kelbet_til_postgres_data:
    driver: local
