import { type Language, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const works = [
  {
    title: "Абдул-Хамид Мархабаев. Шортан планетасы, сен кінәлісің",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "4",
  },
  {
    title: "Асан қайғының жерге айтқан сыны",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "1",
  },
  {
    title: "Аяз би ертегісі",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "1",
  },
  {
    title: "Әйтеке бидің сыншылдығы",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "1",
  },
  {
    title: "Қазыбек би. Кім жақын, не қымбат, не қиын",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "1",
  },
  {
    title: "Қазыбек бидің елшілігі",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "1",
  },
  {
    title: "Қозы Көрпеш Баян сұлу жыры Жанақ нұсқасы",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "2",
  },
  {
    title: "Мұхтар Әуезов «Көксерек»",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "3",
  },
  {
    title: "Түгел сөздің түбі бір, түп атасы – Майқы би. Кімнен кім туады",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "1",
  },
  {
    title: "Шешендік сөздің түрлері",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "1",
  },
  {
    title: "Шешендік сөздер, кезеңі",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "1",
  },
  {
    title: "Шерхан Мұртаза «Жүз жылдық жара» әңгімесі",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "3",
  },
  {
    title: "Өтірік пен шынның арасы",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "1",
  },
  {
    title: "Үйсін Төле би мен Әнет баба",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "1",
  },
  {
    title: "ЛИРА ҚОНЫСБАЙДЫҢ «Ғайып ұл» новелласы",
    fileUrl: "",
    grade: "7",
    language: "T1",
    term: "4",
  },
  {
    title: "Бердібек Соқпақбаев.  Он алты жасар чемпион",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "2",
  },
  {
    title: "Ақұштап Бақтыгереева. Қасқыр өлеңі",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "4",
  },
  {
    title: "Зейнеп Ахметова Шуақты күндер",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "3",
  },
  {
    title: "Мира Сембайқызы. Компьютер",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "3",
  },
  {
    title: "Күләш Ахметова. Пәк табиғат",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "4",
  },
  {
    title: "Ханс Кристиан Андерсон. Сандық самолет",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "1",
  },
  {
    title: "Ыбырай Алтынсарин. Бай баласы мен жарлы баласы",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "2",
  },
  {
    title: "Айбатыр Сейтақ «Қазақстан таулары»",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "1",
  },
  {
    title: "Мира Сембайқызы. Ұялы телефон",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "3",
  },
  {
    title: "Қасым Қайсенов. Жау тылындағы бала",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "4",
  },
  {
    title: "Еркінбай Әкімқұлов Шәмші Қалдаяқов - ән патшасы",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "3",
  },
  {
    title: "«Ақсақ құлан» аңызы",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "3",
  },
  {
    title: "Жюль Верн. Әлемді 80 күн ішінде шарлау",
    fileUrl: "",
    grade: "7",
    language: "T2",
    term: "1",
  },
  {
    title: "Бейімбет Майлин «Қара шелек» әңгімесі",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "1",
  },
  {
    title: "Төлеген Айбергенов  «Аруана – бауыр дүние»",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "3",
  },
  {
    title: "Ыбырай Алтынсарин әңгімелері, ертегілері",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "2",
  },
  {
    title: "Төлеген Айбергенов  «Ана»",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "3",
  },
  {
    title: "Шәкәрім Құдайбердіұлы «Қалқаман-Мамыр» поэмасы",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "1",
  },
  {
    title: "Мағжан Жұмабаев «Батыр Баян» поэмасы",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "1",
  },
  {
    title: "Расул Ғамзатов Менің дағыстаным",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "4",
  },
  {
    title: "Роза Мұқанова «Мәңгілік бала бейне» әңгімесі",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "4",
  },
  {
    title: "Шыңғыс Айтматов. Найман ана",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "2",
  },
  {
    title: "Қадыр Мырза-Әлі «Бабамыздың шоқ басқан табанымен»",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "4",
  },
  {
    title: "Қабдеш Жұмаділов Қаздар қайтып барады",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "3",
  },
  {
    title: "Қадыр Мырза-Әлі «Кәрі қыран»",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "4",
  },
  {
    title: "Мұқағали Мақатаев «Аққулар ұйықтағанда» поэмасы",
    fileUrl: "",
    grade: "8",
    language: "T1",
    term: "3",
  },
  {
    title: "Қадыр Мырзалиев. Қызыл кітап",
    fileUrl: "",
    grade: "8",
    language: "T2",
    term: "3",
  },
  {
    title: "Мұхтар Шаханов «Отырар» поэмасы",
    fileUrl: "",
    grade: "8",
    language: "T2",
    term: "4",
  },
  {
    title: "«Кісі басы бір уыс тұз» тұрмыс-салт ертегісі",
    fileUrl: "",
    grade: "8",
    language: "T2",
    term: "1",
  },
  {
    title: "Шерхан Мұртаза.  Дәрігердің үш қаруы",
    fileUrl: "",
    grade: "8",
    language: "T2",
    term: "2",
  },
  {
    title: "Марат Қабанбаев. Бауыр әңгімесі",
    fileUrl: "",
    grade: "8",
    language: "T2",
    term: "1",
  },
  {
    title: "Әбділдә Тәжібаев «Сырдария» өлеңі",
    fileUrl: "",
    grade: "8",
    language: "T2",
    term: "3",
  },
  {
    title: "Жюль Верн. Су астындағы 80000 км сапар",
    fileUrl: "",
    grade: "8",
    language: "T2",
    term: "3",
  },
  {
    title: "Әзес Несин. «Дүниеде жоқ машина» әңгімесі",
    fileUrl: "",
    grade: "8",
    language: "T2",
    term: "4",
  },
  {
    title: "Талап Сұлтанбеков.  Ғажайып планета",
    fileUrl: "",
    grade: "8",
    language: "T2",
    term: "4",
  },
  {
    title: "Ғалым Әріп. Жел новелла",
    fileUrl: "",
    grade: "8",
    language: "T2",
    term: "2",
  },
  {
    title: "Ілияс Есенберлин. Қаһар",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "3",
  },
  {
    title: "Абай Құнанбаев. Мен жазбаймын өлеңді ермек үшін",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "2",
  },
  {
    title: "Шортанбай Қанайұлы шығармалары_kairan_khalkym",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "2",
  },
  {
    title: "Абай Құнанбаев. Сегіз аяқ",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "2",
  },
  {
    title: "Мұхтар Әуезов.  Хан Кене",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "3",
  },
  {
    title: "Шортанбай Қанайұлы. Зар заман",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "2",
  },
  {
    title: "«Біржан мен Сара» айтысы",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "1",
  },
  {
    title: "Шортанбай Қанайұды шығармалары",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "2",
  },
  {
    title: "Абай Құнанбаев. Ескендір поэмасы",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "2",
  },
  {
    title: "Қыз Жібек операсы",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "1",
  },
  {
    title: "Ғабит Мүсірепов. Ұлпан",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "4",
  },
  {
    title: "Абай Құнанбаев. Малға достың мұңы жоқ малдан басқа",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "2",
  },
  {
    title: "Джек Лондон. Әйел қырық жанды",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "4",
  },
  {
    title: "Абай Құнанбаев «Сабырсыз, арсыз, еріншек»,",
    fileUrl: "",
    grade: "9",
    language: "T1",
    term: "2",
  },
  {
    title: "Әбділхамит Марқабаев. Ғарыштағы қымыз",
    fileUrl: "",
    grade: "9",
    language: "T2",
    term: "4",
  },
  {
    title: "Дүкенбай Досжан. Төрт патшаны көрген кейуана",
    fileUrl: "",
    grade: "9",
    language: "T2",
    term: "2",
  },
  {
    title: "Абай Құнанбаев. Жастықтың оты қайдасың",
    fileUrl: "",
    grade: "9",
    language: "T2",
    term: "4",
  },
  {
    title: "Мұхтар  Әуезов «Көксерек»",
    fileUrl: "",
    grade: "9",
    language: "T2",
    term: "3",
  },
  {
    title: "Тәкен Әлімқұлов. Көкпар әңгімесі",
    fileUrl: "",
    grade: "9",
    language: "T2",
    term: "1",
  },
  {
    title: "Шыңғыс Айтматов. Кассандра танбасы",
    fileUrl: "",
    grade: "9",
    language: "T2",
    term: "3",
  },
  {
    title: "Тәкен Әбдіков. Қонақтар",
    fileUrl: "",
    grade: "9",
    language: "T2",
    term: "3",
  },
  {
    title: "Әзілхан  Нұршайықов «Ақиқат пен аңыз»",
    fileUrl: "",
    grade: "9",
    language: "T2",
    term: "2",
  },
  {
    title: "Дулат Исабеков Қара шаңырақ",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "2",
  },
  {
    title: "Сәкен Сейфуллин Тар жол, тайғақ кешу. ",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "4",
  },
  {
    title: "Ахмет Байтұрсынұлы ШЫҒАРМАЛАР ЖИНАҒЫ",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "3",
  },
  {
    title: "Шоқан Уәлиханов Жоңғария очерктері (үзінді)",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "3",
  },
  {
    title: "БАЛУАН ШОЛАҚ, ҒАЛИЯ",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "1",
  },
  {
    title: "Дулат Исабеков Тіршілік",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "2",
  },
  {
    title: "Ахмет Байтұрсынұлы Қазақтың бас ақыны мақаласы",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "3",
  },
  {
    title: "Ақан Сері (Ақжігіт) Қорамсаұлы «Құлагер» өлеңі",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "1",
  },
  {
    title: "Ілияс Жансүгіров «Құлагер» поэмасы",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "1",
  },
  {
    title: "Үкілі Ыбырыай, Гәкку",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "1",
  },
  {
    title: "Балуан Шолақ Баймырзаұлы «Қыркүйек»",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "1",
  },
  {
    title: "Ақселеу Сейдімбеков Аққыз хикаяты",
    fileUrl: "",
    grade: "10",
    language: "T1",
    term: "2",
  },
  {
    title: "Ерболат Әбікенұлы Пәтер іздеп жүр едік",
    fileUrl: "",
    grade: "10",
    language: "T2",
    term: "3",
  },
  {
    title: "Абай Құнанбаев Ескендір поэмасы",
    fileUrl: "",
    grade: "10",
    language: "T2",
    term: "1",
  },
  {
    title: "Жүсіпбек Аймауытов. Ақбілек романы",
    fileUrl: "",
    grade: "10",
    language: "T2",
    term: "2",
  },
  {
    title: "Ыбырай  Алтынсарин Дүние қалай етсең табылады",
    fileUrl: "",
    grade: "10",
    language: "T2",
    term: "2",
  },
  {
    title: "Қабдеш Жұмаділов Қаздар қайтып барады",
    fileUrl: "",
    grade: "10",
    language: "T2",
    term: "3",
  },
  {
    title: "Думан рамазан Соңғы дем толық",
    fileUrl: "",
    grade: "10",
    language: "T2",
    term: "3",
  },
  {
    title: "Ермек Өтетілеуұлы  Ата заң",
    fileUrl: "",
    grade: "10",
    language: "T2",
    term: "4",
  },
  {
    title: "ЖҮНІС САХИЕВ «Уақыт қайтарымы»",
    fileUrl: "",
    grade: "10",
    language: "T2",
    term: "4",
  },
  {
    title: "Ғабит МҮСІРЕПОВ. ЖАПОН БАЛЛАДАСЫ",
    fileUrl: "",
    grade: "11",
    language: "T1",
    term: "2",
  },
  {
    title:
      "Мұхтар Шаханов. «Құрметсіз, шыншыл тұлғалар немесе Түрік қағанатының құлауы»",
    fileUrl: "",
    grade: "11",
    language: "T1",
    term: "1",
  },
  {
    title: "Эрнест Хемингуэй. Шал мен теңіз",
    fileUrl: "",
    grade: "11",
    language: "T1",
    term: "4",
  },
  {
    title: "Ерлан Жүніс. Менің атым – тәуелсіздік! өлеңі",
    fileUrl: "",
    grade: "11",
    language: "T1",
    term: "1",
  },
  {
    title: "Әшірбек Сығайдың «Сахна Саңлақтары»  еңбегінен үзінді",
    fileUrl: "",
    grade: "11",
    language: "T1",
    term: "4",
  },
  {
    title: "Асқар Алтай. Кентавр әңгімесі",
    fileUrl: "",
    grade: "11",
    language: "T1",
    term: "2",
  },
  {
    title: "Сәкен Жүнісов. Заманай мен Аманай",
    fileUrl: "",
    grade: "11",
    language: "T1",
    term: "4",
  },
  {
    title: "МЕДЕУ СӘРСЕКЕ «Қаныш Сәтпаев» роман-эссе",
    fileUrl: "",
    grade: "11",
    language: "T1",
    term: "1",
  },
  {
    title: "Абай жолы 1",
    fileUrl: "",
    grade: "11",
    language: "T1",
    term: "3",
  },
  {
    title: "Абай жолы 2",
    fileUrl: "",
    grade: "11",
    language: "T1",
    term: "3",
  },
  {
    title: "Абай жолы 3",
    fileUrl: "",
    grade: "11",
    language: "T1",
    term: "3",
  },
  {
    title: "Айзат Рақыш. Жас маманның басынан кешкендері",
    fileUrl: "",
    grade: "11",
    language: "T2",
    term: "3",
  },
  {
    title: "Мұхтар Әуезов. Абай жолы 3-кітап",
    fileUrl: "",
    grade: "11",
    language: "T2",
    term: "4",
  },
  {
    title: "Шоқан Уәлиханов Жоңғария очерктері (үзінді)",
    fileUrl: "",
    grade: "11",
    language: "T2",
    term: "2",
  },
  {
    title: "Роза Мұқанова «Мәңгілік бала бейне» әңгімесі",
    fileUrl: "",
    grade: "11",
    language: "T2",
    term: "1",
  },
  {
    title: "Мұхтар Әуезов. Абай жолы 2-кітап",
    fileUrl: "",
    grade: "11",
    language: "T2",
    term: "4",
  },
  {
    title: "Дүкенбай Досжан. Ар соты",
    fileUrl: "",
    grade: "11",
    language: "T2",
    term: "4",
  },
  {
    title: "Гауһар Сейітжан «Қара алтыны халқымның ...» өлеңі",
    fileUrl: "",
    grade: "11",
    language: "T2",
    term: "3",
  },
  {
    title: "Мұхтар Әуезов. Абай жолы 1-кітап",
    fileUrl: "",
    grade: "11",
    language: "T2",
    term: "4",
  },
  {
    title: "Қадыр Мырзалиев «Аралым»",
    fileUrl: "",
    grade: "11",
    language: "T2",
    term: "2",
  },
  {
    title: "Балғабек Қыдырбекұлы «Қырық құрақ» фельетоны",
    fileUrl: "",
    grade: "11",
    language: "T2",
    term: "3",
  },
  {
    title: "Қыз-Жібек",
    fileUrl: "",
    grade: "11",
    language: "T2",
    term: "1",
  },
  {
    title: "Джек Лондон. Мартин Иден ",
    fileUrl: "",
    grade: "12",
    language: "T1",
    term: "2",
  },
  {
    title: "Мұхтар Әуезов. Қарагөз ",
    fileUrl: "",
    grade: "12",
    language: "T1",
    term: "1",
  },
  {
    title: "Жүсіпбек Аймауытов. Ақбілек романы",
    fileUrl: "",
    grade: "12",
    language: "T1",
    term: "1",
  },
  {
    title: "Ілияс Жансүгіров «Күйші» поэмасы",
    fileUrl: "",
    grade: "12",
    language: "T1",
    term: "2",
  },
  {
    title: "Бауыржан Момышұлы. Қанмен жазылған кітап",
    fileUrl: "",
    grade: "12",
    language: "T1",
    term: "3",
  },
  {
    title: "Мұхтар Шаханов. ТАНАКӨЗ поэмасы",
    fileUrl: "",
    grade: "12",
    language: "T1",
    term: "3",
  },
  {
    title: "Константин Паустовский. Әлемді көру өнері  әңгімесі",
    fileUrl: "",
    grade: "12",
    language: "T1",
    term: "2",
  },
  {
    title: "Жүніс Сахиев. Марстан шыққан жаңғырық",
    fileUrl: "",
    grade: "12",
    language: "T1",
    term: "4",
  },
];

async function main() {
  const books = await prisma.book.createMany({
    data: works.map((work) => ({
      title: work.title,
      fileUrl: work.fileUrl,
      grade: work.grade,
      language: work.language as Language,
      term: work.term,
    })),
  });

  console.log("generated books", books);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })

  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
